### ISSUE TITLE
When getting help for a command don't ask for config params

### ISSUE THREAD

**Issue by acs** [MetricsGrimoire/sortinghat#2]
sortinghat load --help
    Error: No database selected (err: 1046)

For showing the help no other params should be needed.

**Comment by andygrunwald** [comment]
@acs I proposed a fix here: https://github.com/MetricsGrimoire/sortinghat/pull/61
This is not the beautiest one, but it works. Would be cool if you can have a look.

**Comment by sduenas** [comment]
@andygrunwald Your idea works, so for me it's ok.
