### ISSUE TITLE
Error: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)

### ISSUE THREAD

**Issue by andygrunwald** [MetricsGrimoire/sortinghat#20]
```
$ python bin/sortinghat add --name "Max Müller"
Error: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
```

The root cause are there lines (in sortinghat/utils.py):
```python
def uuid(source, email=None, name=None, username=None):
    if source is None:
        raise ValueError('source cannot be None')
    if source == '':
        raise ValueError('source cannot be an empty string')
    if not (email or name or username):
        raise ValueError('identity data cannot be None or empty')

    to_unicode = lambda x: x if type(x) is unicode else unicode(x)

    s = ':'.join((to_unicode(source), to_unicode(email),
                  to_unicode(name), to_unicode(username)))

    sha1 = hashlib.sha1(s.encode('UTF-8'))
    uuid = sha1.hexdigest()

    return uuid
```

The call to `unicode()` is the root cause here.
A minimum example to reproduce:

```python
# -*- coding: utf-8 -*-

name = "Müller"

to_unicode = lambda x: x if type(x) is unicode else unicode(x)
to_unicode(name)
```

This commit https://github.com/MetricsGrimoire/sortinghat/commit/dc7308b3ffbcd45f5b8c82cf4f546b2c895b8af6 introduced the current behaviour.

**Comment by andygrunwald** [comment]
#21 will fix the error not by 100%.
Just execute the command above twice:

```
$ python bin/sortinghat add --name "Max Müller"
New identity 2d16899d8e90dd733a76463ce5878e95da478744 added to 2d16899d8e90dd733a76463ce5878e95da478744
$  sortinghat-fork.git git:(fork-develop) ✗ python bin/sortinghat add --name "Max Müller"
Traceback (most recent call last):
  File "bin/sortinghat", line 175, in <module>
    code = main()
  File "bin/sortinghat", line 87, in main
    code = cmd.run(*args.cmd_args)
  File "/Users/agrunwald/Development/sortinghat-fork.git/sortinghat/cmd/add.py", line 98, in run
    params.uuid, params.matching, params.interactive)
  File "/Users/agrunwald/Development/sortinghat-fork.git/sortinghat/cmd/add.py", line 152, in add
    self.error(str(e))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 18: ordinal not in range(128)
```

**Comment by andygrunwald** [comment]
The latest commit (https://github.com/andygrunwald/sortinghat/commit/0c2288af3e21567d0d9d4577a624efb1e065219e) fixed it. But in my opinion this seems to be a hack.
Whats your opinion?

**Comment by sduenas** [comment]
@andygrunwald Encoding errors in Python are like a pain in the ass and a waste of time. Due to it fixed the problem, for me it's OK.

At some point, my idea is to move the code to Python 3 that fixes all these problems because the strings, by default, are unicode objects.

BTW, I did some changes to your commits before merging them. Just some squash and reword. I hope you don't mind about it.

**Comment by andygrunwald** [comment]
@sduenas Thank you.
I am completly fine with your changes. For me it doesn`t matter as long as it fixed the bug and we can continue develop awesome tools.
