### ISSUE TITLE
Possible unicode issue using mg2sh

### ISSUE THREAD

**Issue by geekygirldawn** [MetricsGrimoire/sortinghat#65]
Running on 14.04.1-Ubuntu
Python 2.7.6
sortinghat cloned from repo and installed on 26 February, 2016

I ran: 
`mg2sh -u *** -p *** -d *** --source scm -o ~/tmp/sortinghat`

And got this error:
`Traceback (most recent call last):
  File "/usr/local/bin/mg2sh", line 170, in <module>
    main()
  File "/usr/local/bin/mg2sh", line 73, in main
    json = to_json(identities, args.source)
  File "/usr/local/bin/mg2sh", line 145, in to_json
    uuid = to_unicode(identity.mg_id)
  File "/usr/local/lib/python2.7/dist-packages/sortinghat/utils.py", line 121, in to_unicode
    return unicode(x.decode('utf-8'))
AttributeError: 'long' object has no attribute 'decode'`

Talking to @dicortazar on IRC who suggested that is was probably a unicode issue here:
https://github.com/MetricsGrimoire/sortinghat/blob/master/sortinghat/utils.py#L121

He suggested that I revert to an earlier version, so I did a:
`git checkout c6bca413aca49f75782ce2b2d71655fe39463b0d`

Which is which is where andy added docker stuff - the Dec 4 version right before I came to Madrid, so I was pretty sure that was a good version. After reinstalling from this checkout, it seems to work fine.

**Comment by sduenas** [comment]
Hi @geekygirldawn ! Thanks for the bug report. I've just fixed it.

There was an error converting integer objects to strings. These objects don't have the `decode` method.
