### ISSUE TITLE
Multiple top domains for CHQSTS-618ZZK1.cable.comcast.com sub-domain

### ISSUE THREAD

**Issue by acs** [MetricsGrimoire/sortinghat#7]
Using affiliate command in Wikimedia identities:

    owl@atari:~/automator/automatic_retrieval/mediawiki$ sortinghat -u root -d acs_sortinghat_mediawiki_5673 affiliate
    ....
    Error: multiple top domains for CHQSTS-618ZZK1.cable.comcast.com sub-domain. Please fix it before continue

**Comment by sduenas** [comment]
It looks like there are two top domains: one for `cable.comcast.com` and another for `comcast.com`. Sorting Hat should be able to choose one of them, in this case, `cable.comcast.com`.
