### ISSUE TITLE
Shouldn't sortinghat.db.database.Database have a "close" method?

### ISSUE THREAD

**Issue by jgbarah** [MetricsGrimoire/sortinghat#70]
I'm using sortinghat.db.database.Database object as arguments to use the stuff in sortinghat.api, such as:

```python
db = sortinghat.db.database.Database(user, password, database, host)
sortinghat.api.add_identity(db=self.db, source="git", email=email, name=name)
```

But I don't see a way of closing the underlying connection that I assume is being open to connect to MySQL. Shouldn't this be provided by a Database.close() method or something?

**Comment by sduenas** [comment]
The short answer is  that SortingHat and SQLAlchemy do all the process under the hood.

The long answer is  `sortinghat.db.database.Database` class has a method `connect` that creates a new session object. This one allows to perform operations with the database (i.e add, delete or search objects).  `connect` method must be called inside a context to get the object and when the transaction is completed it will call to`commit` and `close` for that session. This is the code of `connect` method:
```
@contextmanager
def connect(self):
    session = self._Session()

    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()
```

And this is how it is used in `add_identity` method. Every API method uses `connect` in similar ways:
```
def add_identity(db, source, email=None, name=None, username=None, uuid=None):
    # Some code goes here

    with db.connect() as session:
        # More code goes here to check whether the identity
        # already exists or not

        identity = Identity(id=identity_id, name=name, email=email,
                            username=username, source=source)
        identity.uidentity = uidentity
        session.add(identity)
```

When the code exits from the context (`with` statement), the execution flow is returned to  `db.connect()`. Then, session object calls to `commit` and finally, it calls to `close`.

The call to `close` doesn't really finalizes the session. SQLAlchemy stores a pool of sessions that keep open connections with the database. This avoids the disadvantages of opening and closing connections each time some operation is needed.

More info can be found here:

* http://docs.sqlalchemy.org/en/latest/orm/session_basics.html
* http://docs.sqlalchemy.org/en/latest/core/connections.html
* http://docs.sqlalchemy.org/en/latest/core/pooling.html

**Comment by jgbarah** [comment]
OK, understood. Thanks for the explanation!
