### ISSUE TITLE
[sortinghat] SH is using the wrong name to enrich data

### ISSUE THREAD

**Issue by dpose** [MetricsGrimoire/sortinghat#72]
Sortinghat is using the identities's names (name1, name2...) instead of the profile's name (profile_name) to enrich data.

`sortinghat -d myddbb show profile_uuid
unique identity profile_uuid

Profile:
    * Name: profile_name
    * E-Mail: myemail
    * Bot: No
    * Country: -

Identities:
  uuid1	name1	email1	-	source1
  uuid2	name2	email2	-	source2

Enrollments:
  mycompany	1900-01-01 00:00:00	2100-01-01 00:00:00`

**Comment by sanacl** [comment]
This is not a SH bug but a GrimoireELK bug
